name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [master]

jobs:
  stack:
    name: stack / ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-13, windows-latest]
        stack: ["2.9.3"]
        ghc: ["9.2.7"]
        include:
          - os: ubuntu-latest
            executable: nekofs-linux-x86_64
          - os: ubuntu-20.04
            executable: nekofs-debian-11-x86_64
          - os: macos-13
            executable: nekofs-macos-x86_64
          # - os: macos-latest    # stack is not ready yet
          #   executable: nekofs-macos-aarch64
          - os: windows-latest
            executable: nekofs-windows.exe

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v4
      name: Cache dependencies (Unix)
      if: matrix.os != 'windows-latest'
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - uses: actions/cache@v4
      name: Cache dependencies (Windows)
      if: matrix.os == 'windows-latest'
      with:
        path: |
          ~\AppData\Roaming\stack
          ~\AppData\Local\Programs\stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Install dependencies
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc

    - name: Package
      run: |
        stack install --system-ghc nekofs --local-bin-path=package
        mv package/nekofs* ${{ matrix.executable }}

    - name: Set release tag (Unix)
      if: matrix.os != 'windows-latest'
      run: echo "RELEASE_TAG=v$(stack --system-ghc query locals nekofs version)" >> $GITHUB_ENV

    - name: Set release tag (Windows)
      if: matrix.os == 'windows-latest'
      run: echo "RELEASE_TAG=v$(stack --system-ghc query locals nekofs version)" >> $env:GITHUB_ENV

    - name: Extract release notes
      id: get_changelog
      uses: ffurrer2/extract-release-notes@v2

    - name: Update Release
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        files: ${{ matrix.executable }}
        body: ${{ steps.get_changelog.outputs.release_notes }}

